apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: autoroute-operator
    app.kubernetes.io/name: autoroute-operator
  name: autoroute-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: autoroute-operator
subjects:
- kind: ServiceAccount
  name: autoroute-operator
