apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: petstore-routes
  namespace: default  
spec:
  routes:
  - matcher:
      exact: /petstore/findPet
    routeAction:
      single:
        destinationSpec:
          rest:
            functionName: findPetById
            parameters: {}
        upstream:
          name: default-petstore-8080
          namespace: gloo-system