apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default
  namespace: gloo-system
spec:
  displayName: default
  virtualHost:
    domains:
    - '*'
    routes:
    - matcher:
        prefix: /
      routeAction:
        single:
          upstream:
            name: default-productpage-9080
            namespace: gloo-system
    virtualHostPlugins:
      extensions:
        configs:
          extauth:
            configs:
            - oauth:
                app_url: http://34.70.236.202:80/
                callback_path: /callback
                client_id: G9K48wTJLaFS9PD0R7j4JbRiLUzFSB35
                client_secret_ref:
                  name: auth0
                  namespace: gloo-system
                issuer_url: https://ceposta-solo.auth0.com