---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: purchase-history-v1-error
  labels:
    app: purchase-history-v1-error
spec:
  replicas: 1
  selector:
    matchLabels:
        deploy: purchase-history-v1-error
        version: v1
  template:
    metadata:
      labels:
        app: purchase-history
        deploy: purchase-history-v1-error
        version: v1
      annotations:
    spec:
      containers:
      - name: purchase-history
        image: nicholasjackson/fake-service:v0.7.8
        ports:
        - containerPort: 8080
        env:
        - name: "LISTEN_ADDR"
          value: "0.0.0.0:8080"
        - name: "NAME"
          value: "purchase-history-v1"
        - name: "SERVER_TYPE"
          value: "http"
        - name: "MESSAGE"
          value: "Hello From Purchase History (v1)!"
        - name: "ERROR_RATE"
          value: "0.5"
        - name: "ERROR_CODE"
          value: "503"
        - name: "ERROR_TYPE"
          value: "http_error"
