apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: checkcard-routes
  namespace: default  
spec:
  routes:
  - matchers:
      -  exact: /api/checkcard/check
    routeAction:
      single:
        upstream:
          name: default-echo-server-8080     
          namespace: gloo-system
  - matchers:
      - prefix: /api/checkcard/user
    directResponseAction:
      status: 200        
      body: '{"code": "success"}'    
