apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  labels:
    app: httpbin
  name: default-httpbin-8000
  namespace: gloo-system
spec:
  discoveryMetadata: {}
  kube:
    selector:
      app: httpbin
    serviceName: httpbin
    serviceNamespace: default
    servicePort: 8000
  sslConfig:
    alpn_protocols:
    - istio
    sslFiles:
      rootCa: /etc/istio-certs/root-cert.pem
      tlsCert: /etc/istio-certs/cert-chain.pem
      tlsKey: /etc/istio-certs/key.pem
