apiVersion: devportal.solo.io/v1alpha1
kind: Portal
metadata:
  name: petstore-portal
  namespace: dev-portal
spec:
  banner:
    configMap:
      key: banner-img
      name: dev-portal-petstore-portal-banner-img
      namespace: dev-portal
  customStyling:
    backgroundColor: '#F9F9F9'
    defaultTextColor: '#35393B'
    primaryColor: '#eb921b'
    buttonColorOverride: '#eb921b'
    secondaryColor: '#074d57'
    navigationLinksColorOverride: '#074d57'
  displayName: PetStore Portal
  domains:
  - localhost:1234
  favicon:
    configMap:
      key: favicon
      name: dev-portal-petstore-portal-favicon
      namespace: dev-portal
  primaryLogo:
    configMap:
      key: primary-logo
      name: dev-portal-petstore-portal-primary-logo
      namespace: dev-portal
  publishApiProducts:
    matchLabels:
      portals.devportal.solo.io/dev-portal.petstore-portal: "true"
