---
apiVersion: admiral.io/v1alpha1
kind: GlobalTrafficPolicy
metadata:
  name: gtp-greeting
  namespace: sample
  labels:
    identity: greeting
spec:
  policy:
    - dns: default.greeting.global
      lbType: 1 #0 represents TOPOLOGY, 1 represents FAILOVER
      target:
        - region: us-west1
          weight: 50
        - region: us-central1
          weight: 50
