apiVersion: v1
kind: ServiceAccount
metadata:
  name: webapp
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp
    identity: webapp
  name: webapp
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: webapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
      identity: webapp  
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: webapp
        identity: webapp
    spec:
      containers:
      - command:
        - /bin/sleep
        - 3650d
        image: pstauffer/curl
        imagePullPolicy: IfNotPresent
        name: webapp
      serviceAccountName: webapp
