---
# Source: gloo/templates/2-gloo-usage-configmap.yaml
# use this config map to record envoy usage stats
apiVersion: v1
kind: ConfigMap
metadata:
  name: gloo-usage
  namespace: gloo-system
  labels:
    app: gloo
    gloo: gloo-usage
data: