apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  labels:
    app: productpage
    discovered_by: kubernetesplugin
    service: productpage
  name: bookinfo-productpage-9080
  namespace: gloo-system
spec:
  discoveryMetadata: {}
  sslConfig:
    sds:
      callCredentials:
        fileCredentialSource:
          header: istio_sds_credentials_header-bin
          tokenFileName: /var/run/secrets/tokens/istio-token
      certificatesSecretName: default
      targetUri: unix:/var/run/sds/uds_path
      validationContextName: ROOTCA  
  kube:
    selector:
      app: productpage
    serviceName: productpage
    serviceNamespace: bookinfo
    servicePort: 9080
