apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  labels:
    app: productpage
    discovered_by: kubernetesplugin
    service: productpage
  name: bookinfo-productpage-9080
  namespace: gloo-system
spec:
  discoveryMetadata: {}
  kube:
    selector:
      app: productpage
    serviceName: productpage
    serviceNamespace: bookinfo
    servicePort: 9080
