apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - prefix: /httpbin
      routeAction:
        single:
          upstream:
            name: httpbin-static
            namespace: gloo-system 
      options:
        prefixRewrite: '/headers'               
    - matchers:
      - prefix: /
      routeAction:
        single:
          upstream:
            name: default-web-api-8080
            namespace: gloo-system
    options:
      extauth:
        configRef:
          name: oidc-dex
          namespace: gloo-system             
      stagedTransformations:
        early:
          requestTransforms:
          - requestTransformation:
              transformationTemplate:
                extractors:
                  token:
                    header: 'cookie'
                    regex: 'id_token=(.*); .*'
                    subgroup: 1
                headers:
                  jwt:
                    text: '{{ token }}'  
      headerManipulation:
        requestHeadersToRemove:
        - "cookie"
      jwt:
        providers:
          dex:
            issuer: http://dex.gloo-system.svc.cluster.local:32000
            tokenSource:
              headers:
              - header: Jwt
            claimsToHeaders:
            - claim: email
              header: x-solo-claim-email
            - claim: email_verified
              header: x-solo-claim-email-verified
            jwks:
              remote:
                url: http://dex.gloo-system.svc.cluster.local:32000/keys
                upstreamRef:
                  name: gloo-system-dex-32000 
                  namespace: gloo-system
      rbac:
        policies:
          viewer:
            permissions:
              methods:
              - GET
              pathPrefix: /httpbin
            principals:
            - jwtPrincipal:
                claims:
                  email: admin@example.com
              

