apiVersion: networking.zephyr.solo.io/v1alpha1
kind: TrafficPolicy
metadata:
  namespace: service-mesh-hub
  name: details-tp
spec:
  sourceSelector:
    labels:
      app: productpage
    namespaces:
      - default
  destinationSelector:
    serviceRefs:
      services:
        - name: details
          namespace: default
          cluster: cluster-1
  trafficShift:
    destinations:
      - destination:
          cluster: cluster-1
          name: details
          namespace: default
        weight: 50
        subset:
          version: v1
      - destination:
          cluster: cluster-2
          name: details
          namespace: default
        weight: 50

