apiVersion: networking.zephyr.solo.io/v1alpha1
kind: AccessControlPolicy
metadata:
  namespace: service-mesh-hub
  name: productpage
spec:
  sourceSelector:
    serviceAccountRefs:
      serviceAccounts:
        - name: bookinfo-productpage
          namespace: default
          cluster: cluster-1
  destinationSelector:
    matcher:
      namespaces:
        - default
