apiVersion: networking.smh.solo.io/v1alpha2
kind: TrafficPolicy
metadata:
  namespace: service-mesh-hub
  name: reviews-tp
spec:
  destinationSelector:
  - kubeServiceRefs:
      services:
        - clusterName: cluster-1
          name: reviews
          namespace: default
  trafficShift:
    destinations:
      - kubeService:
          clusterName: cluster-1
          name: reviews
          namespace: default
          subset:
            version: v1          
        weight: 75
      - kubeService:
          clusterName: cluster-1
          name: reviews
          namespace: default
          subset:
            version: v2          
        weight: 25

