apiVersion: networking.zephyr.solo.io/v1alpha1
kind: TrafficPolicy
metadata:
  namespace: service-mesh-hub
  name: simple
spec:
  destinationSelector:
    matcher:
      labels:
        app: reviews
      namespaces: 
        - default
  trafficShift:
    destinations:
      - destination:
          cluster: cluster-2
          name: reviews
          namespace: default
        weight: 75
      - destination:
          cluster: cluster-1
          name: reviews
          namespace: default
        weight: 15
        subset:
          version: v1
      - destination:
          cluster: cluster-1
          name: reviews
          namespace: default
        weight: 10
        subset:
          version: v2
