apiVersion: networking.zephyr.solo.io/v1alpha1
kind: TrafficPolicy
metadata:
  namespace: service-mesh-hub
  name: simple
spec:
  destinationSelector:
    serviceRefs:
      services:
        - cluster: cluster-1
          name: reviews
          namespace: default
  trafficShift:
    destinations:
      - destination:
          cluster: cluster-1
          name: reviews
          namespace: default
        weight: 100
        subset:
          version: v1
      - destination:
          cluster: cluster-1
          name: reviews
          namespace: default
        weight: 0
        subset:
          version: v2
