apiVersion: networking.zephyr.solo.io/v1alpha1
kind: TrafficPolicy
metadata:
  namespace: service-mesh-hub
  name: fault-injection-details
spec:
  sourceSelector:
    labels:
      app: productpage
    namespaces:
      - default
  destinationSelector:
    serviceRefs:
      services:
        - cluster: cluster-1
          name: details
          namespace: default
  faultInjection:
    abort:
      httpStatus: 501
    percentage: 80

