apiVersion: v1
kind: ServiceAccount
metadata:
  name: purchase-history-v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: purchase-history-v1
  labels:
    app: purchase-history-v1
spec:
  replicas: 1
  selector:
    matchLabels:
        deploy: purchase-history-v1
        version: v1
  template:
    metadata:
      labels:
        deploy: purchase-history-v1
        app: purchase-history
        version: v1
      annotations:
        # available consul sm annotations:
        # https://www.consul.io/docs/k8s/connect#available-annotations
        # eg. "consul.hashicorp.com/connect-service-upstreams":"[service-name]:[port]:[optional datacenter]"
        # If you would like to specify multiple services or upstreams, delimit them with commas        
        "consul.hashicorp.com/connect-inject": "true"
        # defaults to first named container on this sepc
        # if set explicit, should be the svc account name
        "consul.hashicorp.com/connect-service": "purchase-history"
        # defaults to first port on the pod spec
        "consul.hashicorp.com/connect-service-port": "8080"
    spec:
      serviceAccountName: purchase-history-v1
      containers:
      - name: purchase-history
        image: nicholasjackson/fake-service:v0.17.0
        ports:
        - containerPort: 8080
        env:
        - name: "LISTEN_ADDR"
          value: "0.0.0.0:8080"
        - name: "NAME"
          value: "purchase-history-v1"
        - name: "SERVER_TYPE"
          value: "http"
        - name: "MESSAGE"
          value: "Hello From Purchase History (v1)!"
---
apiVersion: v1
kind: Service
metadata:
  name: purchase-history
spec:
  selector:
    app: purchase-history
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
