apiVersion: v1
kind: ServiceAccount
metadata:
  name: recommendation
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation
  labels:
    app: recommendation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation
  template:
    metadata:
      labels:
        app: recommendation
      annotations:
        # available consul sm annotations:
        # https://www.consul.io/docs/k8s/connect#available-annotations
        # eg. "consul.hashicorp.com/connect-service-upstreams":"[service-name]:[port]:[optional datacenter]"
        # If you would like to specify multiple services or upstreams, delimit them with commas        
        "consul.hashicorp.com/connect-inject": "true"
        # defaults to first named container on this sepc
        # if set explicit, should be the svc account name
        "consul.hashicorp.com/connect-service": "recommendation"
        # defaults to first port on the pod spec
        "consul.hashicorp.com/connect-service-port": "8080"
        "consul.hashicorp.com/connect-service-upstreams": "purchase-history:9090"
    spec:
      serviceAccountName: recommendation
      containers:
      - name: recommendation
        image: nicholasjackson/fake-service:v0.17.0
        ports:
        - containerPort: 8080
        env:
        - name: "LISTEN_ADDR"
          value: "0.0.0.0:8080"
        - name: "UPSTREAM_URIS"
          value: "http://localhost:9090"
        - name: "NAME"
          value: "recommendation"
        - name: "MESSAGE"
          value: "Hello From Recommendations!"

---
# Service to expose recommendation frontend

apiVersion: v1
kind: Service
metadata:
  name: recommendation
spec:
  selector:
    app: recommendation
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
