apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-api
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-api
  labels:
    app: web-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-api
  template:
    metadata:
      labels:
        app: web-api
      annotations:
        # available consul sm annotations:
        # https://www.consul.io/docs/k8s/connect#available-annotations
        # eg. "consul.hashicorp.com/connect-service-upstreams":"[service-name]:[port]:[optional datacenter]"
        # If you would like to specify multiple services or upstreams, delimit them with commas
        "consul.hashicorp.com/connect-inject": "true"
        # defaults to first named container on this sepc
        # if set explicit, should be the svc account name
        "consul.hashicorp.com/connect-service": "web-api"
        # defaults to first port on the pod spec
        "consul.hashicorp.com/connect-service-port": "8080"
        "consul.hashicorp.com/connect-service-upstreams": "recommendation:9090"
    spec:
      serviceAccountName: web-api
      containers:
      - name: web-api
        image: nicholasjackson/fake-service:v0.17.0
        ports:
        - containerPort: 8080
        env:
        - name: "LISTEN_ADDR"
          value: "0.0.0.0:8080"
        - name: "UPSTREAM_URIS"
          value: "http://localhost:9090"
        - name: "NAME"
          value: "web-api"
        - name: "MESSAGE"
          value: "Hello From Web API"
---          
apiVersion: v1
kind: Service
metadata:
  name: web-api
spec:
  selector:
    app: web-api
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
